server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/

spring:
  application:
    name: gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: course
          uri: http://localhost:8082/ 
          predicates:
            - Path=/course/**
